import 'package:freezed_annotation/freezed_annotation.dart';
part 'equipment.freezed.dart';
part 'equipment.g.dart';

/// Equipment model generated by freezed package.
/// flutter pub run build_runner build --delete-conflicting-outputs
@freezed
class Equipment with _$Equipment {
  const factory Equipment({
    int? id,
    required String? name,
    int? preinstalled,
  }) = _Equipment;

  factory Equipment.fromJson(Map<String, Object?> json) =>
      _$EquipmentFromJson(json);
}
