import 'package:freezed_annotation/freezed_annotation.dart';
part 'exercise.freezed.dart';
part 'exercise.g.dart';

/// Exercise model generated by freezed package.
/// flutter pub run build_runner build --delete-conflicting-outputs
@freezed
class Exercise with _$Exercise {
  const factory Exercise({
    int? id,
    required String? name,
    String? description,
    required int? equipmentId,
    int? preinstalled,
    required int? bars,
    required int? loadId,
    required int? limbs,
  }) = _Exercise;

  factory Exercise.fromJson(Map<String, Object?> json) =>
      _$ExerciseFromJson(json);
}

// import 'package:equatable/equatable.dart';

// /// Exercise model.
// class Exercise extends Equatable {
//   final int? id;
//   final String? name;
//   final String? description;
//   final int? equipmentId;
//   final bool? preinstalled;

//   const Exercise(
//       {this.id,
//       this.name,
//       this.description,
//       this.equipmentId,
//       this.preinstalled});

//   @override
//   List<Object?> get props => [id, name, description];

//   factory Exercise.fromMap(Map<String, dynamic> map) => Exercise(
//         id: map['id'] as int,
//         name: map['name'] == null ? '' : map['name'] as String,
//         description:
//             map['description'] == null ? '' : map['description'] as String,
//         equipmentId: map['equipmentId'] as int,
//       );

//   Map<String, dynamic> toMap() => {
//         'id': id,
//         'name': name,
//         'description': description,
//         'eqipment_id': equipmentId,
//       };
// }
