import 'package:freezed_annotation/freezed_annotation.dart';
part 'exercise.freezed.dart';
part 'exercise.g.dart';

/// Exercise model generated by freezed package.
/// flutter pub run build_runner build --delete-conflicting-outputs
@freezed
class Exercise with _$Exercise {
  const factory Exercise({
    int? id,
    required String? name,
    String? description,
    required int? equipmentId,
    int? preinstalled,
    required int? loadId,
    required int? limbs,
  }) = _Exercise;

  factory Exercise.fromJson(Map<String, Object?> json) =>
      _$ExerciseFromJson(json);
}
