import 'package:freezed_annotation/freezed_annotation.dart';
part 'load.freezed.dart';
part 'load.g.dart';

/// Load model generated by freezed package.
/// flutter pub run build_runner build --delete-conflicting-outputs
@freezed
class Load with _$Load {
  const factory Load({
    int? id,
    required String? name,
    int? preinstalled,
  }) = _Load;

  factory Load.fromJson(Map<String, Object?> json) => _$LoadFromJson(json);
}
