import 'package:freezed_annotation/freezed_annotation.dart';
part 'log_workout.freezed.dart';
part 'log_workout.g.dart';

/// LogWorkout model generated by freezed package.
/// flutter pub run build_runner build --delete-conflicting-outputs
@freezed
class LogWorkout with _$LogWorkout {
  const factory LogWorkout({
    int? id,
    int? repeat,
    int? repeatLeft,
    double? weight,
    double? weightLeft,
    double? distance,
    int? timeLoad,
    String? name,
  }) = _LogWorkout;

  factory LogWorkout.fromJson(Map<String, Object?> json) =>
      _$LogWorkoutFromJson(json);
}
