import 'dart:typed_data' show Uint8List;
import 'package:freezed_annotation/freezed_annotation.dart';
part 'muscle.freezed.dart';
part 'muscle.g.dart';

class Uint8ListConverter implements JsonConverter<Uint8List?, List<int>?> {
  const Uint8ListConverter();

  @override
  Uint8List? fromJson(List<int>? json) {
    return json == null ? null : Uint8List.fromList(json);
  }

  @override
  List<int>? toJson(Uint8List? object) {
    return object?.toList();
  }
}

/// Muscle model generated by freezed package.
/// flutter pub run build_runner build --delete-conflicting-outputs
@freezed
class Muscle with _$Muscle {
  const factory Muscle({
    int? id,
    required String? name,
    @Uint8ListConverter() Uint8List? icon,
  }) = _Muscle;

  factory Muscle.fromJson(Map<String, Object?> json) => _$MuscleFromJson(json);
}
