import 'package:freezed_annotation/freezed_annotation.dart';
part 'workout_set.freezed.dart';
part 'workout_set.g.dart';

/// WorkoutSet model generated by freezed package.
/// flutter pub run build_runner build --delete-conflicting-outputs
@freezed
class WorkoutSet with _$WorkoutSet {
  const factory WorkoutSet({
    int? repeats,
    double? weight,
  }) = _WorkoutSet;

  factory WorkoutSet.fromJson(Map<String, Object?> json) =>
      _$WorkoutSetFromJson(json);
}
