import 'package:freezed_annotation/freezed_annotation.dart';
part 'workout.freezed.dart';
part 'workout.g.dart';

/// Workouts model generated by freezed package.
/// flutter pub run build_runner build --delete-conflicting-outputs
@freezed
class Workout with _$Workout {
  const factory Workout({
    int? id,
    String? name,
    String? description,
    int? ord,
    int? sets,
    int? repeats,
    int? rest,
    int? exercisesId,
    double? weight,
  }) = _Workout;

  factory Workout.fromJson(Map<String, Object?> json) =>
      _$WorkoutFromJson(json);
}
